<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>AFT01</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <org.junit.jupiter.version>5.9.1</org.junit.jupiter.version>
        <org.seleniumhq.selenium.version>4.7.2</org.seleniumhq.selenium.version>
        <com.codeborne.version>6.10.3</com.codeborne.version>
        <org.aeonbits.owner>1.0.12</org.aeonbits.owner>
        <allure.version>2.13.0</allure.version>
        <qameta.allure>2.13.6</qameta.allure>
        <aspectj.version>1.8.10</aspectj.version>
        <allure.maven>2.10.0</allure.maven>
    </properties>
    <dependencies>
        <!--    Это нужно в инструкции для вызова скриншотов по одной из статей.
        Но добавление этого ломает сборку аллюр отчётов!: -->
        <!--        <dependency>-->
        <!--            <groupId>io.qameta.allure</groupId>-->
        <!--            <artifactId>allure-selenide</artifactId>-->
        <!--            <version>2.19.0</version>-->
        <!--            <scope>test</scope>-->
        <!--        </dependency>-->
        <!--        Убрать когда подберу правильную комбинацию зависимостей.-->

        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-params -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>5.9.0</version>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
        <dependency><!--        <Переезжаю на TestNG>-->
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${org.junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${org.seleniumhq.selenium.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-api -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>${org.seleniumhq.selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.htmlelements</groupId>
            <artifactId>htmlelements-java</artifactId>
            <version>1.20.0
            </version> <!-- 1.21+ is SELENIUM 4.1.0 compatible -->
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-common</artifactId>
            <version>2.0b1</version>
        </dependency>

        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>${com.codeborne.version}</version>
        </dependency>
        <dependency>
            <groupId>org.aeonbits.owner</groupId>
            <artifactId>owner</artifactId>
            <version>${org.aeonbits.owner}</version>
            <scope>test</scope>
        </dependency>
<!--        <dependency>--><!--        <Переезжаю на TestNG>-->
<!--            <groupId>io.qameta.allure</groupId>-->
<!--            <artifactId>allure-junit5</artifactId>-->
<!--            <version>${qameta.allure}</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>5.0.0-alpha.11</version>
        </dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp-urlconnection</artifactId>
            <version>5.0.0-alpha.11</version>
        </dependency>

        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>2.20.1</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.testng/testng -->
<!--        <dependency>-->
<!--            <groupId>org.testng</groupId>-->
<!--            <artifactId>testng</artifactId>-->
<!--            <version>6.14.3</version>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->


    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M7</version>
                <configuration>
                    <properties>
                        <configurationParameters>
<!--                            junit.jupiter.conditions.deactivate = *-->
<!--                            junit.jupiter.extensions.autodetection.enabled = true-->
<!--                            junit.jupiter.testinstance.lifecycle.default = per_class-->
<!--                            junit.jupiter.execution.parallel.enabled = true-->
<!--                            junit.jupiter.execution.parallel.mode.default = concurrent-->
                        </configurationParameters>
                    </properties>
                    <testFailureIgnore>false</testFailureIgnore>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                    <systemProperties>
                        <property>
                            <name>
<!--                                autotests.testNG-->
<!--                                junit.jupiter.extensions.autodetection.enabled-->
                            </name>
                            <value>true</value>
                        </property>
                    </systemProperties>
                </configuration>
                <dependencies>
                    <!-- проблема появилась при добавлении этого: начало -->
<!--                    <dependency>-->
<!--                        <groupId>org.junit.platform</groupId>-->
<!--                        <artifactId>junit-platform-surefire-provider</artifactId>-->
<!--                        <version>1.2.0</version>-->
<!--&lt;!&ndash;                        <version>1.3.0-M1</version>&ndash;&gt;-->
<!--                    </dependency>-->
                    <!-- проблема появилась при добавлении этого: конец - -->
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>${allure.maven}</version>
                <configuration>
                    <reportVersion>${allure.version}</reportVersion>
                    <resultsDirectory>${basedir}/allure-results
                    </resultsDirectory>
                    <reportDirectory>${basedir}/target/allure-reports
                    </reportDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>